/*
 * HCVB-Service API
 * This is a API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Openhours
 */
//TODO: Annotation
//@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T12:47:25.920-04:00")
public class Openhours {
  @SerializedName("day")
  private Object day = null;

  @SerializedName("openFrom")
  private Object openFrom = null;

  @SerializedName("openTo")
  private Object openTo = null;

  public Openhours day(Object day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(value = "")
  public Object getDay() {
    return day;
  }

  public void setDay(Object day) {
    this.day = day;
  }

  public Openhours openFrom(Object openFrom) {
    this.openFrom = openFrom;
    return this;
  }

   /**
   * Get openFrom
   * @return openFrom
  **/
  @ApiModelProperty(value = "")
  public Object getOpenFrom() {
    return openFrom;
  }

  public void setOpenFrom(Object openFrom) {
    this.openFrom = openFrom;
  }

  public Openhours openTo(Object openTo) {
    this.openTo = openTo;
    return this;
  }

   /**
   * Get openTo
   * @return openTo
  **/
  @ApiModelProperty(value = "")
  public Object getOpenTo() {
    return openTo;
  }

  public void setOpenTo(Object openTo) {
    this.openTo = openTo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Openhours openhours = (Openhours) o;
    return Objects.equals(this.day, openhours.day) &&
        Objects.equals(this.openFrom, openhours.openFrom) &&
        Objects.equals(this.openTo, openhours.openTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(day, openFrom, openTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Openhours {\n");
    
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    openFrom: ").append(toIndentedString(openFrom)).append("\n");
    sb.append("    openTo: ").append(toIndentedString(openTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

